# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/diffedit',
                'doc_host': 'https://melonkernel.github.io',
                'git_url': 'https://github.com/melonkernel/diffedit',
                'lib_path': 'diffedit'},
  'syms': {'diffedit.core': {'diffedit.core.foo': ('core.html#foo', 'diffedit/core.py')}}}